### PR TITLE
Update script.js/ Firebase

### PR DESCRIPTION
**Pull request by JRProgramming**
Accept this pull request.

### CODE REVIEW

**Comment by Allen-B1** [comment]
ok i'll look into it

**Comment by Allen-B1** [comment]
alright, fixed some formatting issues, will merge

**Comment by JRProgramming** [comment]
K, thanks. I'm going to need you to go to firebase after this

**Comment by Allen-B1** [comment]
k

**Comment by Allen-B1** [comment]
Thx for contributing!

**Comment by JRProgramming** [comment]
NP

**Comment by Allen-B1** [comment]
Merged!

**Comment by Allen-B1** [comment]
Link to issue #10

**Pull request merged**
